### ISSUE TITLE
Crash on MIUI10

### ISSUE THREAD

**Issue by YadrovSergey** [yandexmobile/metrica-plugin-cordova#14]
Crash on MIUI10

java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
at com.yandex.metrica.impl.ob.hj.a(SourceFile:62)
at com.yandex.metrica.impl.ob.hm.a(SourceFile:41)
at com.yandex.metrica.impl.ob.ho$b.handleMessage(SourceFile:62)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/app/com.tvoydnevnik-h_tf7y83IdfAZTLnnQx02A==/base.apk"],nativeLibraryDirectories=[/data/app/com.tvoydnevnik-h_tf7y83IdfAZTLnnQx02A==/lib/arm64, /system/lib64, /vendor/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 6 more

**Comment by YadrovSergey** [comment]
Данная ошибка возникает на Android 9
Пришлось удалить metrica-plugin-cordova

**Comment by NesterovichAlexey** [comment]
Привет. В ближайшие время планируется релиз плагина с последней версией AppMetrica SDK, где этот крэш уже исправлен.

**Comment by vikshv** [comment]
+1

**Comment by lfoma** [comment]
Падает, ломается. Пришлось отключить до лучших времён. Надеюсь на скорую починку.

**Comment by trinitiwowka** [comment]
по прежнему крашится...

**Comment by bigvc** [comment]
+1

**Comment by trinitiwowka** [comment]
не исправлено в релизе 1.0.0?

**Comment by NesterovichAlexey** [comment]
Вышла новая версия плагина. СДК в ней обновлены до последней версии.
Крэш больше не должен воспроизводится.

**Comment by NesterovichAlexey** [comment]
> не исправлено в релизе 1.0.0?

Исправлено. У тебя по прежнему воспроизводится?

**Comment by trinitiwowka** [comment]
Спасибо, проверим в понедельник и отпишусь.
