### ISSUE TITLE
App crash on activate with wrong apiKey

### ISSUE THREAD

**Issue by Rigwarl** [yandexmobile/metrica-plugin-cordova#17]
Приложение падает при попытке активации метрики с неверным ключом.
Насколько я себе представляю плагин для статистики не должен ронять все приложение, даже если не может активироваться и работать по любым причинам.

Android 9

11-22 16:54:46.581 E/AndroidRuntime( 9248): FATAL EXCEPTION: pool-5-thread-1
11-22 16:54:46.581 E/AndroidRuntime( 9248): Process: site.itmagic.magiccasino, PID: 9248
11-22 16:54:46.581 E/AndroidRuntime( 9248): com.yandex.metrica.impl.ob.vu: Invalid ApiKey=debug. Please, read official documentation how to obtain one: https://tech.yandex.com/metrica-mobile-sdk/doc/mobile-sdk-dg/concepts/android-initialize-docpage/
11-22 16:54:46.581 E/AndroidRuntime( 9248): 	at com.yandex.metrica.impl.ob.vt.a(SourceFile:30)
11-22 16:54:46.581 E/AndroidRuntime( 9248): 	at com.yandex.metrica.YandexMetricaConfig$Builder.<init>(SourceFile:198)
11-22 16:54:46.581 E/AndroidRuntime( 9248): 	at com.yandex.metrica.YandexMetricaConfig.newConfigBuilder(SourceFile:146)
11-22 16:54:46.581 E/AndroidRuntime( 9248): 	at com.yandex.metrica.plugin.cordova.AppMetricaPlugin.toConfig(AppMetricaPlugin.java:143)
11-22 16:54:46.581 E/AndroidRuntime( 9248): 	at com.yandex.metrica.plugin.cordova.AppMetricaPlugin.activate(AppMetricaPlugin.java:187)
11-22 16:54:46.581 E/AndroidRuntime( 9248): 	at com.yandex.metrica.plugin.cordova.AppMetricaPlugin.access$000(AppMetricaPlugin.java:30)
11-22 16:54:46.581 E/AndroidRuntime( 9248): 	at com.yandex.metrica.plugin.cordova.AppMetricaPlugin$1.run(AppMetricaPlugin.java:45)
11-22 16:54:46.581 E/AndroidRuntime( 9248): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-22 16:54:46.581 E/AndroidRuntime( 9248): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-22 16:54:46.581 E/AndroidRuntime( 9248): 	at java.lang.Thread.run(Thread.java:764)

**Comment by NesterovichAlexey** [comment]
Привет.
Не соглашусь с тобой. Если плагин не может активироваться, то он должен упасть. Это позволит раньше определить проблему, а не потом выяснять почему нет пользователей и событий на графиках, когда приложение уже будет в проде.

**Comment by Rigwarl** [comment]
Если плагин по какой-то причине не сможет активироваться на проде, он тоже положит все приложение?

**Comment by NesterovichAlexey** [comment]
Да, но проблемы с активацией легко найти при тестировании. Просто запустив приложение.
